Repository ManageIQ/guides, pull requests merged in 2022-02, with the labels that each got.

#484 Switch to GitHub Actions
  .github/workflows/ci.yaml
  .travis.yml
  README.md
Labels: developer, test

#483 Fix Ii8n docs for service ui
  i18n.md
Labels: bug

#486 Add 'security vulnerability' as a scope label
  bin/triage.yml
  triage_process.md
Labels: documentation

#487 Add Najdorf to triage
  bin/triage.yml
  triage_process.md
Labels: enhancement

#479 Update node version
  developer_setup.md
Labels: dependencies

#489 Cron for GitHub Actions
  .github/workflows/ci.yaml
Labels: developer, test
