Repository ManageIQ/guides, pull requests merged in 2024-01, with the labels that each got.

#533 Fix zookeeper/kraft developer setup
  developer_setup.md
Labels: enhancement

#534 Move Kafka into the services section + cleanup
  developer_setup.md
Labels: cleanup, refactoring

#535 Update containerized arch diagram
  architecture/images/Podified Architecture for Jansa.png
  architecture/images/containerized-arch.drawio
  architecture/images/containerized-arch.drawio.png
Labels: documentation

#536 Add Discussions to triage
  triage_process.md
Labels: enhancement

#537 Update arch diagram
  architecture/images/containerized-arch.drawio
  architecture/images/containerized-arch.drawio.png
Labels: documentation
